### ISSUE TITLE
This repository is outdated

### ISSUE THREAD

**Issue by nox** [hsivonen/encoding_c_mem#1]
Latest version is 0.2.4 on crates.io but this is 0.2.2.

**Comment by hsivonen** [comment]
Thanks. Fixed. (This kind of mistake couldn't happen, if `cargo publish` instead of pushing the local files told crates.io "pull this tag from this git repo"...)

**Comment by nox** [comment]
Thanks! Don't forget to take a look at https://github.com/hsivonen/encoding_c_mem/pull/2 please. :)
